# Generated by Django 3.1.2 on 2020-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('experience', models.CharField(choices=[('Training', 'Training'), ('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Training', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('skill', models.ManyToManyField(to='resume.Skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('contribution', models.ManyToManyField(to='resume.Contribution')),
                ('project', models.ManyToManyField(to='resume.Project')),
                ('skill', models.ManyToManyField(to='resume.Skill')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
