# Generated by Django 3.1.2 on 2020-11-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201122_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
