# Generated by Django 3.1.2 on 2020-11-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20201123_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='description',
        ),
    ]
