# Generated by Django 3.1.2 on 2020-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201124_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='   ', max_length=200),
            preserve_default=False,
        ),
    ]
