# Generated by Django 3.1.2 on 2020-11-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='resume.Skill', verbose_name='skill'),
        ),
    ]
