# Generated by Django 3.1.2 on 2020-12-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20201128_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='resume.Skill'),
        ),
    ]
