# Generated by Django 3.1.2 on 2021-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20201201_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote_pct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
